/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiUniverseRouteImport } from './routes/api/universe'
import { Route as ApiPushRegisterRouteImport } from './routes/api/push/register'
import { Route as ApiPushScanRouteImport } from './routes/api/push/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUniverseRoute = ApiUniverseRouteImport.update({
  id: '/api/universe',
  path: '/api/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRegisterRoute = ApiPushRegisterRouteImport.update({
  id: '/api/push/register',
  path: '/api/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushScanRoute = ApiPushScanRouteImport.update({
  id: '/api/push/scan',
  path: '/api/push/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/universe': typeof ApiUniverseRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/push/scan': typeof ApiPushScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/universe': typeof ApiUniverseRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/push/scan': typeof ApiPushScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/universe': typeof ApiUniverseRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/push/scan': typeof ApiPushScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/analyze'
    | '/api/universe'
    | '/api/push/register'
    | '/api/push/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/analyze'
    | '/api/universe'
    | '/api/push/register'
    | '/api/push/scan'
  id:
    | '__root__'
    | '/'
    | '/api/analyze'
    | '/api/universe'
    | '/api/push/register'
    | '/api/push/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiUniverseRoute: typeof ApiUniverseRoute
  ApiPushRegisterRoute: typeof ApiPushRegisterRoute
  ApiPushScanRoute: typeof ApiPushScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/universe': {
      id: '/api/universe'
      path: '/api/universe'
      fullPath: '/api/universe'
      preLoaderRoute: typeof ApiUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/register': {
      id: '/api/push/register'
      path: '/api/push/register'
      fullPath: '/api/push/register'
      preLoaderRoute: typeof ApiPushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/scan': {
      id: '/api/push/scan'
      path: '/api/push/scan'
      fullPath: '/api/push/scan'
      preLoaderRoute: typeof ApiPushScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiUniverseRoute: ApiUniverseRoute,
  ApiPushRegisterRoute: ApiPushRegisterRoute,
  ApiPushScanRoute: ApiPushScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
