/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AvisoDeRiscoRouteImport } from './routes/aviso-de-risco'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'
import { Route as ApiPriceRouteImport } from './routes/api/price'
import { Route as ApiSparklineRouteImport } from './routes/api/sparkline'
import { Route as ApiSyncRouteImport } from './routes/api/sync'
import { Route as ApiUniverseRouteImport } from './routes/api/universe'
import { Route as ApiAdminFlagsRouteImport } from './routes/api/admin/flags'
import { Route as ApiAdminGrantPremiumRouteImport } from './routes/api/admin/grant-premium'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminWhoamiRouteImport } from './routes/api/admin/whoami'
import { Route as ApiAssistantExternalIntelRouteImport } from './routes/api/assistant/external-intel'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingPortalRouteImport } from './routes/api/billing/portal'
import { Route as ApiBillingStatusRouteImport } from './routes/api/billing/status'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing/webhook'
import { Route as ApiNewsFeedRouteImport } from './routes/api/news/feed'
import { Route as ApiNewsPreferencesRouteImport } from './routes/api/news/preferences'
import { Route as ApiOpsAnalysisRouteImport } from './routes/api/ops/analysis'
import { Route as ApiPushRegisterRouteImport } from './routes/api/push/register'
import { Route as ApiPushScanRouteImport } from './routes/api/push/scan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDeRiscoRoute = AvisoDeRiscoRouteImport.update({
  id: '/aviso-de-risco',
  path: '/aviso-de-risco',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPriceRoute = ApiPriceRouteImport.update({
  id: '/api/price',
  path: '/api/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSparklineRoute = ApiSparklineRouteImport.update({
  id: '/api/sparkline',
  path: '/api/sparkline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncRoute = ApiSyncRouteImport.update({
  id: '/api/sync',
  path: '/api/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUniverseRoute = ApiUniverseRouteImport.update({
  id: '/api/universe',
  path: '/api/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFlagsRoute = ApiAdminFlagsRouteImport.update({
  id: '/api/admin/flags',
  path: '/api/admin/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGrantPremiumRoute = ApiAdminGrantPremiumRouteImport.update({
  id: '/api/admin/grant-premium',
  path: '/api/admin/grant-premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWhoamiRoute = ApiAdminWhoamiRouteImport.update({
  id: '/api/admin/whoami',
  path: '/api/admin/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantExternalIntelRoute =
  ApiAssistantExternalIntelRouteImport.update({
    id: '/api/assistant/external-intel',
    path: '/api/assistant/external-intel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingPortalRoute = ApiBillingPortalRouteImport.update({
  id: '/api/billing/portal',
  path: '/api/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStatusRoute = ApiBillingStatusRouteImport.update({
  id: '/api/billing/status',
  path: '/api/billing/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsFeedRoute = ApiNewsFeedRouteImport.update({
  id: '/api/news/feed',
  path: '/api/news/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsPreferencesRoute = ApiNewsPreferencesRouteImport.update({
  id: '/api/news/preferences',
  path: '/api/news/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsAnalysisRoute = ApiOpsAnalysisRouteImport.update({
  id: '/api/ops/analysis',
  path: '/api/ops/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRegisterRoute = ApiPushRegisterRouteImport.update({
  id: '/api/push/register',
  path: '/api/push/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushScanRoute = ApiPushScanRouteImport.update({
  id: '/api/push/scan',
  path: '/api/push/scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviso-de-risco': typeof AvisoDeRiscoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/price': typeof ApiPriceRoute
  '/api/sparkline': typeof ApiSparklineRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/universe': typeof ApiUniverseRoute
  '/api/admin/flags': typeof ApiAdminFlagsRoute
  '/api/admin/grant-premium': typeof ApiAdminGrantPremiumRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/whoami': typeof ApiAdminWhoamiRoute
  '/api/assistant/external-intel': typeof ApiAssistantExternalIntelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/news/feed': typeof ApiNewsFeedRoute
  '/api/news/preferences': typeof ApiNewsPreferencesRoute
  '/api/ops/analysis': typeof ApiOpsAnalysisRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/push/scan': typeof ApiPushScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviso-de-risco': typeof AvisoDeRiscoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/price': typeof ApiPriceRoute
  '/api/sparkline': typeof ApiSparklineRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/universe': typeof ApiUniverseRoute
  '/api/admin/flags': typeof ApiAdminFlagsRoute
  '/api/admin/grant-premium': typeof ApiAdminGrantPremiumRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/whoami': typeof ApiAdminWhoamiRoute
  '/api/assistant/external-intel': typeof ApiAssistantExternalIntelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/news/feed': typeof ApiNewsFeedRoute
  '/api/news/preferences': typeof ApiNewsPreferencesRoute
  '/api/ops/analysis': typeof ApiOpsAnalysisRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/push/scan': typeof ApiPushScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aviso-de-risco': typeof AvisoDeRiscoRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/price': typeof ApiPriceRoute
  '/api/sparkline': typeof ApiSparklineRoute
  '/api/sync': typeof ApiSyncRoute
  '/api/universe': typeof ApiUniverseRoute
  '/api/admin/flags': typeof ApiAdminFlagsRoute
  '/api/admin/grant-premium': typeof ApiAdminGrantPremiumRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/whoami': typeof ApiAdminWhoamiRoute
  '/api/assistant/external-intel': typeof ApiAssistantExternalIntelRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/portal': typeof ApiBillingPortalRoute
  '/api/billing/status': typeof ApiBillingStatusRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/news/feed': typeof ApiNewsFeedRoute
  '/api/news/preferences': typeof ApiNewsPreferencesRoute
  '/api/ops/analysis': typeof ApiOpsAnalysisRoute
  '/api/push/register': typeof ApiPushRegisterRoute
  '/api/push/scan': typeof ApiPushScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aviso-de-risco'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/api/analyze'
    | '/api/price'
    | '/api/sparkline'
    | '/api/sync'
    | '/api/universe'
    | '/api/admin/flags'
    | '/api/admin/grant-premium'
    | '/api/admin/users'
    | '/api/admin/whoami'
    | '/api/assistant/external-intel'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/billing/webhook'
    | '/api/news/feed'
    | '/api/news/preferences'
    | '/api/ops/analysis'
    | '/api/push/register'
    | '/api/push/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aviso-de-risco'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/api/analyze'
    | '/api/price'
    | '/api/sparkline'
    | '/api/sync'
    | '/api/universe'
    | '/api/admin/flags'
    | '/api/admin/grant-premium'
    | '/api/admin/users'
    | '/api/admin/whoami'
    | '/api/assistant/external-intel'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/billing/webhook'
    | '/api/news/feed'
    | '/api/news/preferences'
    | '/api/ops/analysis'
    | '/api/push/register'
    | '/api/push/scan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aviso-de-risco'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/api/analyze'
    | '/api/price'
    | '/api/sparkline'
    | '/api/sync'
    | '/api/universe'
    | '/api/admin/flags'
    | '/api/admin/grant-premium'
    | '/api/admin/users'
    | '/api/admin/whoami'
    | '/api/assistant/external-intel'
    | '/api/auth/$'
    | '/api/billing/checkout'
    | '/api/billing/portal'
    | '/api/billing/status'
    | '/api/billing/webhook'
    | '/api/news/feed'
    | '/api/news/preferences'
    | '/api/ops/analysis'
    | '/api/push/register'
    | '/api/push/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AvisoDeRiscoRoute: typeof AvisoDeRiscoRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiPriceRoute: typeof ApiPriceRoute
  ApiSparklineRoute: typeof ApiSparklineRoute
  ApiSyncRoute: typeof ApiSyncRoute
  ApiUniverseRoute: typeof ApiUniverseRoute
  ApiAdminFlagsRoute: typeof ApiAdminFlagsRoute
  ApiAdminGrantPremiumRoute: typeof ApiAdminGrantPremiumRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAdminWhoamiRoute: typeof ApiAdminWhoamiRoute
  ApiAssistantExternalIntelRoute: typeof ApiAssistantExternalIntelRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingPortalRoute: typeof ApiBillingPortalRoute
  ApiBillingStatusRoute: typeof ApiBillingStatusRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiNewsFeedRoute: typeof ApiNewsFeedRoute
  ApiNewsPreferencesRoute: typeof ApiNewsPreferencesRoute
  ApiOpsAnalysisRoute: typeof ApiOpsAnalysisRoute
  ApiPushRegisterRoute: typeof ApiPushRegisterRoute
  ApiPushScanRoute: typeof ApiPushScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-risco': {
      id: '/aviso-de-risco'
      path: '/aviso-de-risco'
      fullPath: '/aviso-de-risco'
      preLoaderRoute: typeof AvisoDeRiscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/price': {
      id: '/api/price'
      path: '/api/price'
      fullPath: '/api/price'
      preLoaderRoute: typeof ApiPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sparkline': {
      id: '/api/sparkline'
      path: '/api/sparkline'
      fullPath: '/api/sparkline'
      preLoaderRoute: typeof ApiSparklineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync': {
      id: '/api/sync'
      path: '/api/sync'
      fullPath: '/api/sync'
      preLoaderRoute: typeof ApiSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/universe': {
      id: '/api/universe'
      path: '/api/universe'
      fullPath: '/api/universe'
      preLoaderRoute: typeof ApiUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/flags': {
      id: '/api/admin/flags'
      path: '/api/admin/flags'
      fullPath: '/api/admin/flags'
      preLoaderRoute: typeof ApiAdminFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/grant-premium': {
      id: '/api/admin/grant-premium'
      path: '/api/admin/grant-premium'
      fullPath: '/api/admin/grant-premium'
      preLoaderRoute: typeof ApiAdminGrantPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/whoami': {
      id: '/api/admin/whoami'
      path: '/api/admin/whoami'
      fullPath: '/api/admin/whoami'
      preLoaderRoute: typeof ApiAdminWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/external-intel': {
      id: '/api/assistant/external-intel'
      path: '/api/assistant/external-intel'
      fullPath: '/api/assistant/external-intel'
      preLoaderRoute: typeof ApiAssistantExternalIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/portal': {
      id: '/api/billing/portal'
      path: '/api/billing/portal'
      fullPath: '/api/billing/portal'
      preLoaderRoute: typeof ApiBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/status': {
      id: '/api/billing/status'
      path: '/api/billing/status'
      fullPath: '/api/billing/status'
      preLoaderRoute: typeof ApiBillingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/feed': {
      id: '/api/news/feed'
      path: '/api/news/feed'
      fullPath: '/api/news/feed'
      preLoaderRoute: typeof ApiNewsFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/news/preferences': {
      id: '/api/news/preferences'
      path: '/api/news/preferences'
      fullPath: '/api/news/preferences'
      preLoaderRoute: typeof ApiNewsPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/analysis': {
      id: '/api/ops/analysis'
      path: '/api/ops/analysis'
      fullPath: '/api/ops/analysis'
      preLoaderRoute: typeof ApiOpsAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/register': {
      id: '/api/push/register'
      path: '/api/push/register'
      fullPath: '/api/push/register'
      preLoaderRoute: typeof ApiPushRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/scan': {
      id: '/api/push/scan'
      path: '/api/push/scan'
      fullPath: '/api/push/scan'
      preLoaderRoute: typeof ApiPushScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AvisoDeRiscoRoute: AvisoDeRiscoRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiPriceRoute: ApiPriceRoute,
  ApiSparklineRoute: ApiSparklineRoute,
  ApiSyncRoute: ApiSyncRoute,
  ApiUniverseRoute: ApiUniverseRoute,
  ApiAdminFlagsRoute: ApiAdminFlagsRoute,
  ApiAdminGrantPremiumRoute: ApiAdminGrantPremiumRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAdminWhoamiRoute: ApiAdminWhoamiRoute,
  ApiAssistantExternalIntelRoute: ApiAssistantExternalIntelRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingPortalRoute: ApiBillingPortalRoute,
  ApiBillingStatusRoute: ApiBillingStatusRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiNewsFeedRoute: ApiNewsFeedRoute,
  ApiNewsPreferencesRoute: ApiNewsPreferencesRoute,
  ApiOpsAnalysisRoute: ApiOpsAnalysisRoute,
  ApiPushRegisterRoute: ApiPushRegisterRoute,
  ApiPushScanRoute: ApiPushScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
